[package]
name = "jaesve"
version = "0.8.1"
authors = ["Baz <github(a)luxolus.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0.34"
clap = "2.32.0"
regex = "1"
simplelog = "0.6.0"
log = "0.4.8"
lazy_static = "1.3.0"